import { z } from 'zod';

export const CreateRvdVendaSchema = z.object({
  loja_idloja: z.number().int().positive(),
  departamento_iddepartamento: z.string().max(2),
  chassi: z.string().max(17).nullable().optional(),
  nro_proposta: z.number().int().nullable().optional(),
  empresa_origem_proposta: z.number().int().nullable().optional(),
  revenda_origem_proposta: z.number().int().nullable().optional(),
  chave_proposta_loja_dms: z.string().max(50),
  id_usuario_dms: z.number().int().nullable().optional(),
  nome_usuario_dms: z.string().max(100).nullable().optional(),
  cpf_usuario_dms: z.number().nullable().optional(),
  departamento_usuario_dms: z.number().int().nullable().optional(),
  time_venda_dms: z.number().int().nullable().optional(),
  nome_time_venda_dms: z.string().max(100).nullable().optional(),
  status_a_faturar: z.enum(['REALIZADO', 'PENDENTE', 'DEVOLVIDO']).nullable().optional(),
  veiculo_capturado: z.string().max(100).nullable().optional(),
  valor_sinal: z.number().nullable().optional(),
  valor_compra: z.number().nullable().optional(),
  correcao_faturamento: z.number().nullable().optional(),
  bonus: z.number().nullable().optional(),
  outros_bonus: z.number().nullable().optional(),
  bonus_complementar: z.number().nullable().optional(),
  tipo_bonus_complementar: z.string().max(30).nullable().optional(),
  acessorios: z.number().nullable().optional(),
  acessorios_nf: z.number().nullable().optional(),
  outros_nf: z.number().nullable().optional(),
  brinde: z.number().nullable().optional(),
  valor_financiado: z.number().nullable().optional(),
  banco: z.string().max(50).nullable().optional(),
  valor_consorcio: z.number().nullable().optional(),
  consorcio: z.string().max(50).nullable().optional(),
  tabela: z.number().int().nullable().optional(),
  despachante: z.number().nullable().optional(),
  seguro: z.number().nullable().optional(),
  despesas_vendas: z.number().nullable().optional(),
  plus_antecipado: z.number().nullable().optional(),
  top: z.number().nullable().optional(),
  devolucao: z.boolean().default(false),
  a_faturar_premium: z.object({
    dta_venda: z.string(),
    dta_nf: z.string().nullable().optional(),
    tipo_veiculo: z.enum(['CARRO', 'MOTO']),
    dta_entrada_estoque: z.string().nullable().optional(),
    venda_nro: z.number().nullable().optional(),
    nf_nro: z.number().nullable().optional(),
    pedido: z.string(),
    cliente: z.string(),
    modelo: z.string(),
    tipo_venda: z.string(),
    local_venda: z.string(),
    valor_nota_venda: z.number(),
    valor_nf_fabrica: z.number().nullable().optional(),
  }).nullable().optional(),
  historico: z.array(z.object({
    data: z.string(),
    usuario: z.string(),
    descricao: z.record(z.string(), z.unknown()),
  })).nullable().optional(),
});

export type CreateRvdVendaDto = z.infer<typeof CreateRvdVendaSchema>;