SELECT
  A.COD_EMPRESA AS ID_EMPRESA,
  A.COD_PROPOSTA AS PROPOSTA,
  V.CHASSI_COMPLETO AS CHASSI,
  UPPER(EU.NOME_COMPLETO) AS NOME_VENDEDOR,
  EU.ID_FUNCIONARIO AS ID_VENDEDOR,
  EU.CPF AS CPF_VENDEDOR,
  EU.COD_EMPRESA_DEPARTAMENTO AS TIME_VENDA,
  ED.DESCRICAO AS DES_TIME_VENDA,
  A.NOME_CLIENTE AS NOME_CLIENTE,
  B.DESCRICAO_MODELO AS MODELO,
  'DEVOLVIDO' AS STATUS
FROM VEICULOS_PROPOSTAS A
JOIN PRODUTOS_MODELOS B ON A.COD_PRODUTO = B.COD_PRODUTO AND A.COD_MODELO = B.COD_MODELO
JOIN EMPRESAS_USUARIOS EU ON A.VENDEDOR = EU.NOME
LEFT JOIN VEICULOS V ON A.COD_PRODUTO = V.COD_PRODUTO
  AND A.COD_MODELO = V.COD_MODELO
  AND A.CHASSI_RESUMIDO = V.CHASSI_RESUMIDO
  AND A.COD_EMPRESA = V.COD_EMPRESA
LEFT JOIN EMPRESAS_DEPARTAMENTOS ED ON ED.COD_EMPRESA = EU.COD_EMPRESA
  AND ED.COD_EMPRESA_DEPARTAMENTO = EU.COD_EMPRESA_DEPARTAMENTO
WHERE A.STATUS_PROPOSTA = 'C'
AND V.CHASSI_COMPLETO IS NOT NULL
:filterString