SELECT
  EU.COD_EMPRESA AS EMPRESA,
  ED.COD_EMPRESA_DEPARTAMENTO AS TIME_VENDA_DMS,
  ED.COD_EMPRESA_DEPARTAMENTO AS DEPARTAMENTO_USUARIO_DMS,
  ED.DESCRICAO AS NOME_TIME_VENDA_DMS,
  UPPER(EU.NOME_COMPLETO) AS NOME,
  EU.CPF AS CPF_USUARIO,
  CASE WHEN EU.ID_FUNCIONARIO IS NULL THEN 0 ELSE EU.ID_FUNCIONARIO END ID_VENDEDOR
FROM EMPRESAS_USUARIOS EU
INNER JOIN EMPRESAS_DEPARTAMENTOS ED
  ON EU.COD_EMPRESA_DEPARTAMENTO = ED.COD_EMPRESA_DEPARTAMENTO
  AND EU.COD_EMPRESA = ED.COD_EMPRESA
INNER JOIN EMPRESAS_DIVISOES EDIV
  ON EU.COD_EMPRESA_DIVISAO = EDIV.COD_EMPRESA_DIVISAO
  AND ED.COD_EMPRESA = EDIV.COD_EMPRESA
  AND ED.COD_EMPRESA_DEPARTAMENTO = EDIV.COD_EMPRESA_DEPARTAMENTO
WHERE EU.USUARIO_PRINCIPAL IS NULL
AND EU.COD_FUNCAO <> 37
AND EU.DEMITIDO <> 'S'
:filterString