-- CreateTable
CREATE TABLE `rvd_venda` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `loja_idloja` INTEGER NOT NULL,
    `departamento_iddepartamento` VARCHAR(2) NOT NULL,
    `chassi` VARCHAR(17) NULL,
    `nro_proposta` INTEGER NULL,
    `empresa_origem_proposta` INTEGER NULL,
    `revenda_origem_proposta` INTEGER NULL,
    `chave_proposta_loja_dms` VARCHAR(50) NOT NULL,
    `id_usuario_dms` INTEGER NULL,
    `nome_usuario_dms` VARCHAR(100) NULL,
    `cpf_usuario_dms` BIGINT NULL,
    `departamento_usuario_dms` INTEGER NULL,
    `time_venda_dms` INTEGER NULL,
    `nome_time_venda_dms` VARCHAR(100) NULL,
    `status_a_faturar` VARCHAR(20) NULL,
    `veiculo_capturado` VARCHAR(100) NULL,
    `valor_sinal` DECIMAL(10, 2) NULL DEFAULT 0,
    `valor_compra` DECIMAL(10, 2) NULL DEFAULT 0,
    `correcao_faturamento` DECIMAL(10, 2) NULL DEFAULT 0,
    `bonus` DECIMAL(10, 2) NULL DEFAULT 0,
    `outros_bonus` DECIMAL(10, 2) NULL DEFAULT 0,
    `bonus_complementar` DECIMAL(10, 2) NULL DEFAULT 0,
    `tipo_bonus_complementar` VARCHAR(30) NULL,
    `acessorios` DECIMAL(10, 2) NULL DEFAULT 0,
    `acessorios_nf` DECIMAL(10, 2) NULL DEFAULT 0,
    `outros_nf` DECIMAL(10, 2) NULL DEFAULT 0,
    `brinde` DECIMAL(10, 2) NULL DEFAULT 0,
    `valor_financiado` DECIMAL(10, 2) NULL DEFAULT 0,
    `banco` VARCHAR(50) NULL,
    `valor_consorcio` DECIMAL(10, 2) NULL DEFAULT 0,
    `consorcio` VARCHAR(50) NULL,
    `tabela` INTEGER NULL,
    `despachante` DECIMAL(10, 2) NULL DEFAULT 0,
    `seguro` DECIMAL(10, 2) NULL DEFAULT 0,
    `despesas_vendas` DECIMAL(10, 2) NULL DEFAULT 0,
    `plus_antecipado` DECIMAL(10, 2) NULL DEFAULT 0,
    `top` DECIMAL(10, 2) NULL DEFAULT 0,
    `devolucao` BOOLEAN NOT NULL DEFAULT false,
    `a_faturar_premium` JSON NULL,
    `historico` JSON NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `rvd_venda_loja_idloja_idx`(`loja_idloja`),
    INDEX `rvd_venda_loja_idloja_departamento_iddepartamento_idx`(`loja_idloja`, `departamento_iddepartamento`),
    INDEX `rvd_venda_chave_proposta_loja_dms_idx`(`chave_proposta_loja_dms`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
